spring:
  datasource:
    url: jdbc:h2:~/sssa
    username: sa
    password: 12
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create

      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  config:
    import: file:application-secret.yml
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
