spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sssa
    username: sa
    password: 12
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update






